name: Deploy Page
on:
    push:
        branches:
            - main
jobs:
    deploy-page:
        runs-on: ubuntu-latest
        steps:
            - name: Install NPM
              run: sudo apt-get install -y npm
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Install NPM Deps
              run: npm install
            - name: Build Pages
              run: npm run build
            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2
            - name: Deploy
              run: aws s3 sync ./dist s3://player.runningstream.cc --delete
